package com.navidam.sdk.internal.meme;
public enum MemeTemplate {

    AAG("aag", "Ancient Aliens Guy", 2),
    ACKBAR("ackbar", "It's A Trap!", 2),
    AFRAID("afraid", "Afraid to Ask Andy", 2),
    AGNES("agnes", "Agnes Harkness Winking", 2),
    AINT_GOT_TIME("aint-got-time", "Sweet Brown", 2),
    AMS("ams", "Awkward Moment Seal", 2),
    ANTS("ants", "Do You Want Ants?", 2),
    APCR("apcr", "Almost Politically Correct Redneck", 2),
    ASTRONAUT("astronaut", "Always Has Been", 4),
    ATIS("atis", "And Then I Said", 2),
    AWAY("away", "Life... Finds a Way", 2),
    AWESOME("awesome", "Socially Awesome Penguin", 2),
    AWESOME_AWKWARD("awesome-awkward", "Socially Awesome Awkward Penguin", 2),
    AWKWARD("awkward", "Socially Awkward Penguin", 2),
    AWKWARD_AWESOME("awkward-awesome", "Socially Awkward Awesome Penguin", 2),
    BAD("bad", "You Should Feel Bad", 2),
    BADCHOICE("badchoice", "Milk Was a Bad Choice", 2),
    BALLOON("balloon", "Running Away Balloon", 3),
    BD("bd", "Butthurt Dweller", 2),
    BECAUSE("because", "Men in Black", 2),
    BENDER("bender", "I'm Going to Build My Own Theme Park", 2),
    BIHW("bihw", "But It's Honest Work", 2),
    BILBO("bilbo", "Why Shouldn't I Keep It", 2),
    BIW("biw", "Baby Insanity Wolf", 2),
    BLB("blb", "Bad Luck Brian", 2),
    BOAT("boat", "I Should Buy a Boat Cat", 2),
    BONGO("bongo", "Bongo Cat", 2),
    BOTH("both", "Why Not Both?", 2),
    BOX("box", "What's in the box!?", 2),
    BS("bs", "This is Bull, Shark", 2),
    BUS("bus", "Two Guys on a Bus", 2),
    BUZZ("buzz", "X, X Everywhere", 2),
    CAKE("cake", "Office Space Milton", 2),
    CAPTAIN("captain", "I am the Captain Now", 2),
    CAPTAIN_AMERICA("captain-america", "Captain America Elevator Fight Dad Joke", 3),
    CB("cb", "Confession Bear", 2),
    CBB("cbb", "Communist Bugs Bunny", 2),
    CBG("cbg", "Comic Book Guy", 2),
    CENTER("center", "What is this, a Center for Ants?!", 2),
    CH("ch", "Captain Hindsight", 2),
    CHAIR("chair", "American Chopper Argument", 6),
    CHEEMS("cheems", "Cheems", 2),
    CHOSEN("chosen", "You Were the Chosen One!", 2),
    CMM("cmm", "Change My Mind", 1),
    COUNTRY("country", "What a Country", 2),
    CRAZYPILLS("crazypills", "I Feel Like I'm Taking Crazy Pills", 2),
    CROW("crow", "Get Better Material", 2),
    CRYINGFLOOR("cryingfloor", "Crying on Floor", 2),
    DB("db", "Distracted Boyfriend", 3),
    DBG("dbg", "Expectation vs. Reality", 2),
    DG("dg", "Distracted Girlfriend", 3),
    DISASTERGIRL("disastergirl", "Disaster Girl", 2),
    DODGSON("dodgson", "See? Nobody Cares", 2),
    DOGE("doge", "Doge", 2),
    DRAGON("dragon", "What Color Do You Want Your Dragon", 1),
    DRAKE("drake", "Drakeposting", 2),
    DROWNING("drowning", "Drowning High Five", 3),
    DRUNK("drunk", "Drunk Baby", 2),
    DS("ds", "Daily Struggle", 3),
    DSM("dsm", "Dating Site Murderer", 2),
    DWIGHT("dwight", "Schrute Facts", 2),
    ELF("elf", "You Sit on a Throne of Lies", 2),
    ELMO("elmo", "Elmo Choosing Cocaine", 5),
    ERMG("ermg", "Ermahgerd", 2),
    EXIT("exit", "Left Exit 12 Off Ramp", 3),
    FA("fa", "Forever Alone", 2),
    FACEPALM("facepalm", "Facepalm", 2),
    FBF("fbf", "Foul Bachelor Frog", 2),
    FEELSGOOD("feelsgood", "Feels Good", 2),
    FETCH("fetch", "Stop Trying to Make Fetch Happen", 2),
    FINE("fine", "This is Fine", 2),
    FIRSTTRY("firsttry", "First Try!", 2),
    FMR("fmr", "Fuck Me, Right?", 2),
    FRIENDS("friends", "Are You Two Friends?", 3),
    FRY("fry", "Futurama Fry", 2),
    FWP("fwp", "First World Problems", 2),
    GANDALF("gandalf", "Confused Gandalf", 2),
    GB("gb", "Galaxy Brain", 4),
    GEARS("gears", "You Know What Really Grinds My Gears?", 2),
    GENIE("genie", "Genie Lamp", 2),
    GGG("ggg", "Good Guy Greg", 2),
    GLASSES("glasses", "Peter Parker's Glasses", 2),
    GONE("gone", "And It's Gone", 2),
    GRAVE("grave", "Grant Gustin Next To Oliver Queen's Grave", 3),
    GRU("gru", "Gru's Plan", 4),
    GRUMPYCAT("grumpycat", "Grumpy Cat", 2),
    HAGRID("hagrid", "I Should Not Have Said That", 2),
    HANDSHAKE("handshake", "Epic Handshake", 3),
    HAPPENING("happening", "It's Happening", 2),
    HAROLD("harold", "Hide the Pain Harold", 2),
    HEADACHES("headaches", "Types of Headaches", 1),
    HIPSTER("hipster", "Hipster Barista", 2),
    HOME("home", "We Have Food at Home", 3),
    ICANHAS("icanhas", "I Can Has Cheezburger?", 2),
    IMSORRY("imsorry", "Oh, I'm Sorry, I Thought This Was America", 2),
    INIGO("inigo", "Inigo Montoya", 2),
    INTERESTING("interesting", "The Most Interesting Man in the World", 2),
    IVE("ive", "Jony Ive Redesigns Things", 2),
    IW("iw", "Insanity Wolf", 2),
    JD("jd", "Joseph Ducreux", 2),
    JETPACK("jetpack", "Nothing To Do Here", 2),
    JIM("jim", "Jim Halpert Pointing to Whiteboard", 2),
    JOKER("joker", "It's Simple, Kill the Batman", 2),
    JW("jw", "Probably Not a Good Idea", 2),
    KEANU("keanu", "Conspiracy Keanu", 2),
    KERMIT("kermit", "But That's None of My Business", 2),
    KHABY_LAME("khaby-lame", "Khaby Lame Shrug", 2),
    KK("kk", "Karate Kyle", 2),
    KOMBUCHA("kombucha", "Kombucha Girl", 2),
    KRAMER("kramer", "Kramer, What's Going On In There?", 2),
    LEO("leo", "Leo Strutting", 2),
    LIGHT("light", "Everything the Light Touches is Our Kingdom", 2),
    LIVE("live", "Do It Live!", 2),
    LL("ll", "Laughing Lizard", 2),
    LRV("lrv", "Laundry Room Viking", 2),
    MADE("made", "I Made This", 5),
    MB("mb", "Member Berries", 2),
    MICHAEL_SCOTT("michael-scott", "Michael Scott No God No", 2),
    MIDWIT("midwit", "Midwit", 3),
    MILLERS("millers", "You Guys Are Getting Paid?", 4),
    MINI_KEANU("mini-keanu", "Mini Keanu Reeves", 2),
    MMM("mmm", "Minor Mistake Marvin", 2),
    MONEY("money", "Shut Up and Take My Money!", 2),
    MORDOR("mordor", "One Does Not Simply Walk into Mordor", 2),
    MORPHEUS("morpheus", "Matrix Morpheus", 2),
    MOUTH("mouth", "Woman Holding Dog's Mouth", 3),
    MW("mw", "I Guarantee It", 2),
    NAILS("nails", "Guy Hammering Nails Into Sand", 3),
    NICE("nice", "So I Got That Goin' For Me, Which is Nice", 2),
    NOAH("noah", "What the Hell is This?", 4),
    NOIDEA("noidea", "I Have No Idea What I'm Doing", 2),
    NTOT("ntot", "No Take, Only Throw", 3),
    OAG("oag", "Overly Attached Girlfriend", 2),
    OFFICESPACE("officespace", "That Would Be Great", 2),
    OLDER("older", "An Older Code Sir, But It Checks Out", 2),
    OPRAH("oprah", "Oprah You Get a Car", 2),
    PANIK_KALM_PANIK("panik-kalm-panik", "Panik Kalm Panik", 3),
    PATRICK("patrick", "Push it somewhere else Patrick", 2),
    PERFECTION("perfection", "Perfection", 6),
    PERSIAN("persian", "Persian Cat Room Guardian", 2),
    PHILOSORAPTOR("philosoraptor", "Philosoraptor", 2),
    PIGEON("pigeon", "Is This a Pigeon?", 3),
    POOH("pooh", "Tuxedo Winnie the Pooh", 2),
    POOL("pool", "Mother Ignoring Kid Drowning In A Pool", 3),
    PROP3("prop3", "Too Confusing, Too Extreme", 1),
    PTJ("ptj", "Phoebe Teaching Joey", 8),
    PUFFIN("puffin", "Unpopular opinion puffin", 2),
    RED("red", "Oh, Is That What We're Going to Do Today?", 2),
    REGRET("regret", "I Immediately Regret This Decision!", 2),
    REMEMBERS("remembers", "Pepperidge Farm Remembers", 2),
    REVEAL("reveal", "Scooby Doo Reveal", 4),
    RIGHT("right", "Anakin and Padme Change the World For the Better", 5),

    // Duplicado en tu JSON con distinto número de líneas
    ROLLSAFE_2("rollsafe", "Roll Safe", 2),
    ROLLSAFE_1("rollsafe", "Roll Safe", 1),

    SAD_BIDEN("sad-biden", "Sad Joe Biden", 2),
    SAD_BOEHNER("sad-boehner", "Sad John Boehner", 2),
    SAD_BUSH("sad-bush", "Sad George Bush", 2),
    SAD_CLINTON("sad-clinton", "Sad Bill Clinton", 2),
    SAD_OBAMA("sad-obama", "Sad Barack Obama", 2),
    SADFROG("sadfrog", "Feels Bad Man", 2),
    SALTBAE("saltbae", "Salt Bae", 2),
    SAME("same", "They're The Same Picture", 3),
    SARCASTICBEAR("sarcasticbear", "Sarcastic Bear", 2),
    SAY("say", "Say the Line, Bart!", 2),
    SB("sb", "Scumbag Brain", 2),
    SCC("scc", "Sudden Clarity Clarence", 2),
    SEAGULL("seagull", "Inhaling Seagull", 2),
    SF("sf", "Sealed Fate", 2),
    SK("sk", "Skeptical Third World Kid", 2),
    SKI("ski", "Super Cool Ski Instructor", 2),
    SLAP("slap", "Will Smith Slapping Chris Rock", 2),
    SNEK("snek", "Skeptical Snake", 2),
    SOA("soa", "Seal of Approval", 2),
    SOHAPPY("sohappy", "I Would Be So Happy", 2),
    SOHOT("sohot", "So Hot Right Now", 2),
    SOUP_NAZI("soup-nazi", "No Soup for You", 2),
    SPARTA("sparta", "This is Sparta!", 2),
    SPIDERMAN("spiderman", "Spider-Man Pointing at Spider-Man", 2),
    SPIRIT("spirit", "Fake Spirit Halloween Costume", 5),
    SPONGEBOB("spongebob", "Mocking Spongebob", 2),
    SS("ss", "Scumbag Steve", 2),
    STEW("stew", "Baby, You've Got a Stew Going", 2),
    STONKS("stonks", "Stonks", 2),
    STOP("stop", "Stop It Patrick You're Scaring Him", 6),
    STOP_IT("stop-it", "Stop It, Get Some Help", 2),
    SUCCESS("success", "Success Kid", 2),
    TENGUY("tenguy", "10 Guy", 2),
    TOOHIGH("toohigh", "The Rent Is Too Damn High", 2),
    TOUCH("touch", "Principal Skinner", 2),
    TRIED("tried", "At Least You Tried", 2),
    TRUMP("trump", "Donald Trump", 2),
    UGANDANKNUCK("ugandanknuck", "Ugandan Knuckles", 2),
    VINCE("vince", "Vince McMahon Reaction", 3),
    WALLET("wallet", "Patrick Star's Wallet", 8),
    WAYGD("waygd", "What Are Ya Gonna Do?", 2),
    WDDTH("wddth", "We Don't Do That Here", 2),
    WHATYEAR("whatyear", "What Year Is It?", 2),
    WINTER("winter", "Winter is coming", 2),
    WISHES("wishes", "Genie Rules", 1),
    WKH("wkh", "Who Killed Hannibal?", 3),
    WOMAN_CAT("woman-cat", "Woman Yelling at a Cat", 2),
    WONKA("wonka", "Condescending Wonka", 2),
    WORST("worst", "The Worst Day Of Your Life So Far", 2),
    XY("xy", "X all the Y", 2),
    YALLGOT("yallgot", "Y'all Got Any More of Them", 2),
    YODAWG("yodawg", "Xzibit Yo Dawg", 2),
    YUNO("yuno", "Y U NO Guy", 2),
    ZERO_WING("zero-wing", "All Your Base Are Belong to Us", 1);

    private final String id;
    private final String displayName;
    private final int lines;

    MemeTemplate(String id, String displayName, int lines) {
        this.id = id;
        this.displayName = displayName;
        this.lines = lines;
    }


    public static MemeTemplate fromId(String id) {
        for (MemeTemplate t : values()) {
            if (t.id.equalsIgnoreCase(id)) return t;
        }
        throw new IllegalArgumentException("Template id no soportado: " + id);
    }

    public String id() {
        return id;
    }

    public String displayName() {
        return displayName;
    }

    public int lines() {
        return lines;
    }
}
